enum Shapeselection { cube, sphere, cylinder, null1 }

//List<String,String> patternlst = ["assets/bluecamo.jpg",'CamoFlauge']

List<String> items = [
  'Gradienta',
  'Sean',
  'Pawel',
  'PawelPink',
  'PinkWaves',
  'BiaAndre',
  'BlueCamo',
  'GreenCamo',
  'RedCamo',
  'WhiteCamo',
  'DenseForest',
  'BirMinGham',
  'SocialCut',
  'VintageWay',
  'WhiteGeo',
  'GradientGeo',
  'Ridley',
  'Dust',
  'RedFlow',
];

List<String> itemsvalue = [
  "assets/Gradienta.jpg",
  "assets/sean.jpg",
  "assets/Pawel.jpg",
  "assets/pawelPink.jpg",
  "assets/PinkWaves.jpg",
  "assets/BiaAndrade.jpg",
  "assets/BlueCamo.jpg",
  "assets/GreenCamo.jpg",
  "assets/RedCamo.jpg",
  "assets/WhiteCamo.jpg",
  "assets/DenseForest.jpg",
  "assets/birmingham.jpg",
  "assets/SocialCut.jpg",
  "assets/VintageWay.jpg",
  "assets/WhiteGeo.jpg",
  "assets/GradientGeo.jpg",
  "assets/Ridley.jpg",
  "assets/Dust.jpg",
  "assets/RedFlow.jpg",
];

// Map items = {
//   'Gradienta': "assets/Pattern/gradienta.jpg",
//   'Sean': "assets/Pattern/sean.jpg",
//   'Pawel': "assets/Pattern/Pawel.jpg",
//   'PawelPink': "assets/Pattern/pawelPink.jpg",
//   'PinkWaves': "assets/Pattern/PinkWaves.jpg",
//   'BiaAndre': "assets/Pattern/BiaAndrade.jpg",
//   'BlueCamo': "assets/Pattern/BlueCamo.jpg",
//   'GreenCamo': "assets/Pattern/GreenCamo.jpg",
//   'RedCamo': "assets/Pattern/RedCamo.jpg",
//   'WhiteCamo': "assets/Pattern/WhiteCamo.jpg",
//   'DenseForest': "assets/Pattern/DenseForest.jpg",
//   'BirMinGham': "assets/Pattern/birmingham.jpg",
//   'SocialCut': "assets/Pattern/SocialCut.jpg",
//   'VintageWay': "assets/Pattern/VintageWay.jpg",
//   'WhiteGeo': "assets/Pattern/WhiteGeo.jpg",
//   'GradientGeo': "assets/Pattern/GradientGeo.jpg",
//   'Ridley': "assets/Pattern/Ridley.jpg",
//   'Dust': "assets/Pattern/Dust.jpg",
//   'RedFlow': "assets/Pattern/RedFlow.jpg",
// };
